// Code generated by protoc-gen-go.
// source: proto_files/message.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	proto_files/message.proto

It has these top-level messages:
	GenMessage
	Login
	MoveTo
	PlayerMoveTo
	PlayerLogin
	GenReplyMsg
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type GenMessage struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GenMessage) Reset()                    { *m = GenMessage{} }
func (m *GenMessage) String() string            { return proto.CompactTextString(m) }
func (*GenMessage) ProtoMessage()               {}
func (*GenMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GenMessage) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GenMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Login struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Login) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type MoveTo struct {
	X                *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	DirX             *float32 `protobuf:"fixed32,3,req,name=dirX" json:"dirX,omitempty"`
	DirY             *float32 `protobuf:"fixed32,4,req,name=dirY" json:"dirY,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MoveTo) Reset()                    { *m = MoveTo{} }
func (m *MoveTo) String() string            { return proto.CompactTextString(m) }
func (*MoveTo) ProtoMessage()               {}
func (*MoveTo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MoveTo) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *MoveTo) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *MoveTo) GetDirX() float32 {
	if m != nil && m.DirX != nil {
		return *m.DirX
	}
	return 0
}

func (m *MoveTo) GetDirY() float32 {
	if m != nil && m.DirY != nil {
		return *m.DirY
	}
	return 0
}

type PlayerMoveTo struct {
	Id               *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	X                *float32 `protobuf:"fixed32,2,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,3,req,name=y" json:"y,omitempty"`
	DirX             *float32 `protobuf:"fixed32,4,req,name=dirX" json:"dirX,omitempty"`
	DirY             *float32 `protobuf:"fixed32,5,req,name=dirY" json:"dirY,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlayerMoveTo) Reset()                    { *m = PlayerMoveTo{} }
func (m *PlayerMoveTo) String() string            { return proto.CompactTextString(m) }
func (*PlayerMoveTo) ProtoMessage()               {}
func (*PlayerMoveTo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlayerMoveTo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *PlayerMoveTo) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PlayerMoveTo) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *PlayerMoveTo) GetDirX() float32 {
	if m != nil && m.DirX != nil {
		return *m.DirX
	}
	return 0
}

func (m *PlayerMoveTo) GetDirY() float32 {
	if m != nil && m.DirY != nil {
		return *m.DirY
	}
	return 0
}

type PlayerLogin struct {
	Id               *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	X                *float32 `protobuf:"fixed32,2,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,3,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlayerLogin) Reset()                    { *m = PlayerLogin{} }
func (m *PlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*PlayerLogin) ProtoMessage()               {}
func (*PlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerLogin) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *PlayerLogin) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PlayerLogin) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type GenReplyMsg struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	IsReply          *bool   `protobuf:"varint,2,req,name=isReply" json:"isReply,omitempty"`
	Data             []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GenReplyMsg) Reset()                    { *m = GenReplyMsg{} }
func (m *GenReplyMsg) String() string            { return proto.CompactTextString(m) }
func (*GenReplyMsg) ProtoMessage()               {}
func (*GenReplyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GenReplyMsg) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GenReplyMsg) GetIsReply() bool {
	if m != nil && m.IsReply != nil {
		return *m.IsReply
	}
	return false
}

func (m *GenReplyMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GenMessage)(nil), "messages.GenMessage")
	proto.RegisterType((*Login)(nil), "messages.Login")
	proto.RegisterType((*MoveTo)(nil), "messages.MoveTo")
	proto.RegisterType((*PlayerMoveTo)(nil), "messages.PlayerMoveTo")
	proto.RegisterType((*PlayerLogin)(nil), "messages.PlayerLogin")
	proto.RegisterType((*GenReplyMsg)(nil), "messages.GenReplyMsg")
}

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x8f, 0x4f, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5,
	0x03, 0x8b, 0x09, 0x71, 0x40, 0xb9, 0xc5, 0x4a, 0x1a, 0x5c, 0x5c, 0xee, 0xa9, 0x79, 0xbe, 0x10,
	0xae, 0x10, 0x0f, 0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04, 0xa3, 0x02, 0x93, 0x06, 0x27, 0x88,
	0x97, 0x92, 0x58, 0x92, 0x28, 0xc1, 0x04, 0xe4, 0xf1, 0x28, 0x09, 0x73, 0xb1, 0xfa, 0xe4, 0xa7,
	0x67, 0xe6, 0x09, 0x71, 0x71, 0x31, 0x65, 0xa6, 0x40, 0x94, 0x28, 0x59, 0x71, 0xb1, 0xf9, 0xe6,
	0x97, 0xa5, 0x86, 0xe4, 0x0b, 0x71, 0x72, 0x31, 0x56, 0x80, 0x05, 0x99, 0x40, 0xcc, 0x4a, 0xb0,
	0x26, 0x26, 0xb0, 0x11, 0x99, 0x45, 0x11, 0x12, 0xcc, 0x48, 0xbc, 0x48, 0x09, 0x16, 0x10, 0x4f,
	0xc9, 0x87, 0x8b, 0x27, 0x20, 0x27, 0xb1, 0x32, 0xb5, 0x08, 0x6a, 0x02, 0x92, 0xb9, 0x10, 0xd3,
	0x98, 0x10, 0xa6, 0x31, 0xa3, 0x98, 0xc6, 0x82, 0x62, 0x1a, 0x2b, 0xd8, 0x34, 0x7d, 0x2e, 0x6e,
	0x88, 0x69, 0x18, 0x8e, 0xc4, 0x6e, 0x18, 0xd0, 0xe9, 0xdc, 0x40, 0x9f, 0x07, 0xa5, 0x16, 0xe4,
	0x54, 0xfa, 0x16, 0xa7, 0xa3, 0x79, 0x9d, 0x9f, 0x8b, 0x3d, 0xb3, 0x18, 0x2c, 0x07, 0xd6, 0xc8,
	0x01, 0x0f, 0x0b, 0x90, 0x5e, 0x1e, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0xb7, 0x7a, 0x80,
	0x5b, 0x01, 0x00, 0x00,
}
