// Code generated by protoc-gen-go.
// source: proto_files/message.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	proto_files/message.proto

It has these top-level messages:
	GenMessage
	Login
	PlayerState
	LoginReply
	StartPath
	PlayerStartPath
	MoveTo
	PlayerMoveTo
	PlayerLogin
	PlayerQuit
	GenReplyMsg
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type GenMessage struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GenMessage) Reset()                    { *m = GenMessage{} }
func (m *GenMessage) String() string            { return proto.CompactTextString(m) }
func (*GenMessage) ProtoMessage()               {}
func (*GenMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GenMessage) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GenMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Login struct {
	EquipId          *string `protobuf:"bytes,1,req,name=equipId" json:"equipId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Login) GetEquipId() string {
	if m != nil && m.EquipId != nil {
		return *m.EquipId
	}
	return ""
}

type PlayerState struct {
	Index            *int32   `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	X                *float32 `protobuf:"fixed32,2,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,3,req,name=y" json:"y,omitempty"`
	ColorIndex       *int32   `protobuf:"varint,4,req,name=colorIndex" json:"colorIndex,omitempty"`
	Level            *int32   `protobuf:"varint,5,req,name=level" json:"level,omitempty"`
	Exp              *int32   `protobuf:"varint,6,req,name=exp" json:"exp,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlayerState) Reset()                    { *m = PlayerState{} }
func (m *PlayerState) String() string            { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()               {}
func (*PlayerState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerState) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *PlayerState) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PlayerState) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *PlayerState) GetColorIndex() int32 {
	if m != nil && m.ColorIndex != nil {
		return *m.ColorIndex
	}
	return 0
}

func (m *PlayerState) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerState) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

type LoginReply struct {
	ErrorCode        *int32         `protobuf:"varint,1,opt,name=errorCode,def=0" json:"errorCode,omitempty"`
	MyState          *PlayerState   `protobuf:"bytes,2,opt,name=myState" json:"myState,omitempty"`
	Players          []*PlayerState `protobuf:"bytes,3,rep,name=players" json:"players,omitempty"`
	Timestamp        *int64         `protobuf:"varint,4,opt,name=timestamp,def=0" json:"timestamp,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_LoginReply_ErrorCode int32 = 0
const Default_LoginReply_Timestamp int64 = 0

func (m *LoginReply) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_LoginReply_ErrorCode
}

func (m *LoginReply) GetMyState() *PlayerState {
	if m != nil {
		return m.MyState
	}
	return nil
}

func (m *LoginReply) GetPlayers() []*PlayerState {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *LoginReply) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return Default_LoginReply_Timestamp
}

type StartPath struct {
	Sx               *float32 `protobuf:"fixed32,1,req,name=sx" json:"sx,omitempty"`
	Sy               *float32 `protobuf:"fixed32,2,req,name=sy" json:"sy,omitempty"`
	Dx               *float32 `protobuf:"fixed32,3,req,name=dx" json:"dx,omitempty"`
	Dy               *float32 `protobuf:"fixed32,4,req,name=dy" json:"dy,omitempty"`
	Timestamp        *int64   `protobuf:"varint,5,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StartPath) Reset()                    { *m = StartPath{} }
func (m *StartPath) String() string            { return proto.CompactTextString(m) }
func (*StartPath) ProtoMessage()               {}
func (*StartPath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StartPath) GetSx() float32 {
	if m != nil && m.Sx != nil {
		return *m.Sx
	}
	return 0
}

func (m *StartPath) GetSy() float32 {
	if m != nil && m.Sy != nil {
		return *m.Sy
	}
	return 0
}

func (m *StartPath) GetDx() float32 {
	if m != nil && m.Dx != nil {
		return *m.Dx
	}
	return 0
}

func (m *StartPath) GetDy() float32 {
	if m != nil && m.Dy != nil {
		return *m.Dy
	}
	return 0
}

func (m *StartPath) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type PlayerStartPath struct {
	Index            *int32   `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	Sx               *float32 `protobuf:"fixed32,2,req,name=sx" json:"sx,omitempty"`
	Sy               *float32 `protobuf:"fixed32,3,req,name=sy" json:"sy,omitempty"`
	Dx               *float32 `protobuf:"fixed32,4,req,name=dx" json:"dx,omitempty"`
	Dy               *float32 `protobuf:"fixed32,5,req,name=dy" json:"dy,omitempty"`
	Timestamp        *int64   `protobuf:"varint,6,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlayerStartPath) Reset()                    { *m = PlayerStartPath{} }
func (m *PlayerStartPath) String() string            { return proto.CompactTextString(m) }
func (*PlayerStartPath) ProtoMessage()               {}
func (*PlayerStartPath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerStartPath) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *PlayerStartPath) GetSx() float32 {
	if m != nil && m.Sx != nil {
		return *m.Sx
	}
	return 0
}

func (m *PlayerStartPath) GetSy() float32 {
	if m != nil && m.Sy != nil {
		return *m.Sy
	}
	return 0
}

func (m *PlayerStartPath) GetDx() float32 {
	if m != nil && m.Dx != nil {
		return *m.Dx
	}
	return 0
}

func (m *PlayerStartPath) GetDy() float32 {
	if m != nil && m.Dy != nil {
		return *m.Dy
	}
	return 0
}

func (m *PlayerStartPath) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type MoveTo struct {
	X                *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	DirX             *float32 `protobuf:"fixed32,3,req,name=dirX" json:"dirX,omitempty"`
	DirY             *float32 `protobuf:"fixed32,4,req,name=dirY" json:"dirY,omitempty"`
	Timestamp        *int64   `protobuf:"varint,5,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MoveTo) Reset()                    { *m = MoveTo{} }
func (m *MoveTo) String() string            { return proto.CompactTextString(m) }
func (*MoveTo) ProtoMessage()               {}
func (*MoveTo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MoveTo) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *MoveTo) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *MoveTo) GetDirX() float32 {
	if m != nil && m.DirX != nil {
		return *m.DirX
	}
	return 0
}

func (m *MoveTo) GetDirY() float32 {
	if m != nil && m.DirY != nil {
		return *m.DirY
	}
	return 0
}

func (m *MoveTo) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type PlayerMoveTo struct {
	Index            *int32   `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	X                *float32 `protobuf:"fixed32,2,req,name=x" json:"x,omitempty"`
	Y                *float32 `protobuf:"fixed32,3,req,name=y" json:"y,omitempty"`
	DirX             *float32 `protobuf:"fixed32,4,req,name=dirX" json:"dirX,omitempty"`
	DirY             *float32 `protobuf:"fixed32,5,req,name=dirY" json:"dirY,omitempty"`
	Timestamp        *int64   `protobuf:"varint,6,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlayerMoveTo) Reset()                    { *m = PlayerMoveTo{} }
func (m *PlayerMoveTo) String() string            { return proto.CompactTextString(m) }
func (*PlayerMoveTo) ProtoMessage()               {}
func (*PlayerMoveTo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlayerMoveTo) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *PlayerMoveTo) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PlayerMoveTo) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *PlayerMoveTo) GetDirX() float32 {
	if m != nil && m.DirX != nil {
		return *m.DirX
	}
	return 0
}

func (m *PlayerMoveTo) GetDirY() float32 {
	if m != nil && m.DirY != nil {
		return *m.DirY
	}
	return 0
}

func (m *PlayerMoveTo) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type PlayerLogin struct {
	PlayerData       *PlayerState `protobuf:"bytes,1,req,name=playerData" json:"playerData,omitempty"`
	Timestamp        *int64       `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PlayerLogin) Reset()                    { *m = PlayerLogin{} }
func (m *PlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*PlayerLogin) ProtoMessage()               {}
func (*PlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PlayerLogin) GetPlayerData() *PlayerState {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

func (m *PlayerLogin) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type PlayerQuit struct {
	Index            *int32 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerQuit) Reset()                    { *m = PlayerQuit{} }
func (m *PlayerQuit) String() string            { return proto.CompactTextString(m) }
func (*PlayerQuit) ProtoMessage()               {}
func (*PlayerQuit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PlayerQuit) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type GenReplyMsg struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	IsReply          *bool   `protobuf:"varint,2,opt,name=isReply,def=0" json:"isReply,omitempty"`
	Data             []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GenReplyMsg) Reset()                    { *m = GenReplyMsg{} }
func (m *GenReplyMsg) String() string            { return proto.CompactTextString(m) }
func (*GenReplyMsg) ProtoMessage()               {}
func (*GenReplyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

const Default_GenReplyMsg_IsReply bool = false

func (m *GenReplyMsg) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GenReplyMsg) GetIsReply() bool {
	if m != nil && m.IsReply != nil {
		return *m.IsReply
	}
	return Default_GenReplyMsg_IsReply
}

func (m *GenReplyMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GenMessage)(nil), "messages.GenMessage")
	proto.RegisterType((*Login)(nil), "messages.Login")
	proto.RegisterType((*PlayerState)(nil), "messages.PlayerState")
	proto.RegisterType((*LoginReply)(nil), "messages.LoginReply")
	proto.RegisterType((*StartPath)(nil), "messages.StartPath")
	proto.RegisterType((*PlayerStartPath)(nil), "messages.PlayerStartPath")
	proto.RegisterType((*MoveTo)(nil), "messages.MoveTo")
	proto.RegisterType((*PlayerMoveTo)(nil), "messages.PlayerMoveTo")
	proto.RegisterType((*PlayerLogin)(nil), "messages.PlayerLogin")
	proto.RegisterType((*PlayerQuit)(nil), "messages.PlayerQuit")
	proto.RegisterType((*GenReplyMsg)(nil), "messages.GenReplyMsg")
}

var fileDescriptor0 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x96, 0x9d, 0xa6, 0xdd, 0x4e, 0x83, 0x56, 0x58, 0x80, 0x82, 0xb8, 0xa0, 0x1c, 0x50, 0xb8,
	0x14, 0xc4, 0x71, 0x6f, 0x08, 0x24, 0xb4, 0x82, 0xa0, 0xe5, 0xe7, 0x00, 0x27, 0xe4, 0xdd, 0xcc,
	0x16, 0x4b, 0x69, 0x1d, 0x6c, 0xef, 0x2a, 0x79, 0x03, 0x1e, 0x1b, 0x7b, 0x9c, 0x2e, 0x69, 0x51,
	0x24, 0x6e, 0xf3, 0x75, 0xa6, 0xdf, 0x4f, 0x66, 0x0c, 0x8f, 0x5b, 0xa3, 0x9d, 0xfe, 0x71, 0xad,
	0x1a, 0xb4, 0x2f, 0xb6, 0x68, 0xad, 0xdc, 0xe0, 0x9a, 0x7e, 0x13, 0x27, 0x03, 0xb4, 0x45, 0x09,
	0xf0, 0x0e, 0x77, 0x55, 0x84, 0x22, 0x83, 0x99, 0xeb, 0x5b, 0xcc, 0xd9, 0x53, 0x5e, 0x2e, 0x03,
	0xaa, 0xa5, 0x93, 0x39, 0xf7, 0x28, 0x2b, 0x72, 0x48, 0x3f, 0xe8, 0x8d, 0xda, 0x89, 0x53, 0x58,
	0xe0, 0xaf, 0x1b, 0xd5, 0x9e, 0xd7, 0x71, 0xae, 0xb8, 0x84, 0xd5, 0x45, 0x23, 0x7b, 0x34, 0x5f,
	0x9c, 0x74, 0x28, 0xee, 0x41, 0xaa, 0x76, 0x35, 0x76, 0xd4, 0x4d, 0xc5, 0x12, 0x58, 0x47, 0x14,
	0x3c, 0x94, 0x7d, 0x9e, 0x50, 0x29, 0x00, 0xae, 0x74, 0xa3, 0xcd, 0x39, 0x4d, 0xce, 0x68, 0xd2,
	0xff, 0xb1, 0xc1, 0x5b, 0x6c, 0xf2, 0x94, 0xe0, 0x0a, 0x12, 0xec, 0xda, 0x7c, 0x1e, 0x40, 0xf1,
	0x9b, 0x01, 0x90, 0xfc, 0x67, 0x6c, 0x9b, 0x5e, 0x3c, 0x80, 0x25, 0x1a, 0xa3, 0xcd, 0x1b, 0x5d,
	0x07, 0xb7, 0xac, 0x4c, 0xcf, 0xd8, 0x4b, 0xf1, 0x0c, 0x16, 0xdb, 0x9e, 0x4c, 0x78, 0x41, 0x56,
	0xae, 0x5e, 0x3d, 0x5c, 0xef, 0x83, 0xae, 0xc7, 0x0e, 0xfd, 0x5c, 0x4b, 0xd0, 0x7a, 0x37, 0xc9,
	0xf4, 0x9c, 0x57, 0x71, 0xca, 0x77, 0x9c, 0xdc, 0xb6, 0xde, 0x23, 0x2b, 0x13, 0xaf, 0x52, 0x7c,
	0x84, 0xa5, 0x6f, 0x1b, 0x77, 0x21, 0xdd, 0x4f, 0x1f, 0x83, 0xdb, 0x98, 0x94, 0x53, 0xdd, 0x0f,
	0x51, 0x7d, 0x5d, 0x77, 0x43, 0xd6, 0x50, 0xf7, 0x94, 0x91, 0x8b, 0xfb, 0x63, 0xca, 0x90, 0x33,
	0x29, 0xae, 0xe0, 0xf4, 0x4e, 0x74, 0x60, 0x3d, 0xfa, 0x84, 0x51, 0x84, 0x8f, 0x44, 0x92, 0x91,
	0xc8, 0x6c, 0x24, 0x92, 0xfe, 0x2b, 0x32, 0x27, 0x91, 0x0a, 0xe6, 0x95, 0xbe, 0xc5, 0xaf, 0x3a,
	0xee, 0x83, 0xfd, 0xdd, 0x47, 0xa4, 0x0d, 0xbb, 0x56, 0xe6, 0xdb, 0x40, 0x1c, 0xd1, 0xf7, 0x69,
	0xcf, 0x97, 0x90, 0x45, 0xcf, 0x03, 0xe9, 0x7f, 0xed, 0x7c, 0xaf, 0x31, 0x3b, 0xd0, 0x98, 0xb4,
	0xfc, 0x7e, 0x7f, 0x56, 0xf1, 0xec, 0x9e, 0x03, 0xc4, 0xa5, 0xbd, 0x0d, 0x37, 0x19, 0x74, 0x26,
	0xf7, 0x76, 0x40, 0xc6, 0x89, 0xec, 0x09, 0x40, 0x9c, 0xf8, 0x74, 0xa3, 0xdc, 0x91, 0xdd, 0xe2,
	0x35, 0xac, 0xfc, 0x23, 0xa0, 0xcb, 0xaa, 0xec, 0xe6, 0xe8, 0x15, 0x3c, 0x82, 0x85, 0xb2, 0xd4,
	0xa3, 0xa3, 0x3a, 0x39, 0x4b, 0xaf, 0x65, 0x63, 0xf1, 0xee, 0x75, 0x84, 0x6c, 0xd9, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x1c, 0xe9, 0x7b, 0x13, 0x6d, 0x03, 0x00, 0x00,
}
